### ISSUE TITLE
Can´t generate ores?

### ISSUE THREAD

**Issue by CountOmega** [Terrails/OreController#7]
Hi Terrails,
I´m running you latest mod for generating custom ore sizes.
Config file says 

```
# Configuration file

"general settings" {
    B:Generate=true

    #  [default: ]
    S:"Ore Generation" <
	minecraft:iron_ore -minVein:3 -maxVein:5 -minY:40 -maxY:100 -perChunk:7 -dimension:0
	
	>
}
```

Upon generation I´m getting the error

```
[14:27:49] [Server thread/INFO] [Ore Controller]: Block '' is invalid
[14:27:49] [Server thread/INFO] [Ore Controller]: config Value doesn't contain required variables: 
```
I´m running MC 1.12.2 with Forge 14.23.5.2779. Could you help me out?

**Comment by Terrails** [comment]
I was wondering why it was happening but after checking its because you have one empty line beneath the iron_ore, its trying to read it and cant find anything. I should probably look for this case so it doesn't print an error for nothing. Anyways I'll probably start updating the mod to 1.14+ in a couple of months and switch to a json system probably, since its easier and much more straightforward to use. I haven't given this mod a proper treatment yet.
