### ISSUE TITLE
correct names and ore generation

### ISSUE THREAD

**Issue by Gachanx** [Terrails/OreController#8]
Minecraft Version: 1.12.2
Forge Version: build 2847
OreController Version: 1.0.12

Hello,

I can't get the mod to generate ores from mods like industrialcraft2 or railcraft, tried every name i could find in the respective mods files. Also tried it with different mods (like pixelmon, from a comment posted on the mods curseforge page) and it works, so i don't know if the issue is that i haven't found the correct ore/mod id names or something else.
Maybe you already have a config for ores from those mods or other tech mods i could use, that would probably help a lot already.

[ore_controller.log](https://github.com/Terrails/OreController/files/4024118/ore_controller.log)

**Comment by Terrails** [comment]
You're using wrong names for every item. IC2 and Railcraft use metadata for their blocks in 1.12 or lower. Copper ore from IC2 is "ic2:resource" and the metadata is "1". So you would have "ic2:resource|1" instead of "ic2:copper_ore". 

I'm pretty sure you can check that when you enable additional tooltips (F3 + H, or something along those lines) and then you should see "ic2:resource" under the name and a number after a "/" in the brackets for the metadata number. You usually have to use metadata (aka "|" and the number after the registry name) if that number is anything above 0

**Comment by Gachanx** [comment]
It works, thank you for the quick response.
Also works in BiomesOPlenty.
